### ISSUE TITLE
Interact with Google Play Store

### ISSUE THREAD

**Issue by sibelius** [mattwilson1024/android-pattern-unlock#5]
http://stackoverflow.com/questions/37923618/is-there-any-android-automation-robot

I want to create a script that will:
- Open Google Play Store app
- Download my application
- Mark it as always update
- Mark all the others applications to not update at all

Do u think it is possible to achieve this using only adb?

is there any better tool to handle this? without need to know the specific pixels positions?

**Comment by mattwilson1024** [comment]
Closed as this is not an issue with this script.

I'm not sure how you'd go about doing that, but don't think adb touch input would be a very good approach because it would require exact customisation for each device / Android variant / screen size etc and might also have unexpected results if notifications popped up during the execution etc.

I think it also depends on how much control you have over the devices, whether they are rooted, whether the device type(s) and software versions are known etc.
